---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAMESPACE}
objects:
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    name: ${NAMESPACE}
  description: '${NAMESPACE_DESCRIPTION}' 
  displayName: '${NAMESPACE_DISPLAY_NAME}'
parameters:
- description: Name
  displayName: Name
  name: NAMESPACE
  required: true
- description: DisplayName
  displayName: DisplayName
  name: NAMESPACE_DISPLAY_NAME
  required: true
- description: Description
  displayName: Description
  name: NAMESPACE_DESCRIPTION