# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: node-express-mongo-app
baseImage: nodejs:12-ubi8
targetPort: 8080
replicaCount: 1
databaseConnectionString: mongodb://mongodb:27017
  
mongodb:
  fullnameOverride: mongodb #override name so that it isn't pinned to release name
  auth:
    enabled: false
  persistence:
    enabled: true
  containerSecurityContext:
    enabled: false
  podSecurityContext:
    enabled: false




  

config:
  enabled: true
  name: config-map-app
  values:
    DATABASE_URL: mongodb://mongodb:27017
    PORT: 8080

secret:
  enabled: true
  name: secret-app
  values:
    DATABASE_URL: mongodb://mongodb:27017
    PORT: 8080