{{- if .Values.deployment.config.enabled }}
{{- with .Values.deployment.config}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
data:
  {{- range $key, $val := .values }}
    {{ $key }}: {{ $val | quote }}
  {{- end}}
{{- end}}
{{- end}}