{{- if .Values.config.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
data:
  {{- range $key, $val := .Values.config.values }}
    {{ $key }}: {{ $val | quote }}
  {{- end}}
{{- end}}