apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"{{ .Values.appName }}:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"{{ .Values.appName }}\")].image"}]'
  labels:
    app: {{ .Values.appName }}
    app.kubernetes.io/component: {{ .Values.appName }}
    app.kubernetes.io/instance: {{ .Values.appName }}
  name: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      deployment: {{ .Values.appName }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        deployment: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.appName }}:latest
        {{- if .Values.config.enabled}}
        envFrom:
        - configMapRef:
            name: {{ .Values.config.name }}
        {{- end}}
        ports:
        - containerPort: {{ .Values.targetPort }}
        {{- if .Values.secret.enabled}}
        volumeMounts:
        - name: secret-volume-mount
          mountPath: /etc/secret-volume
      volumes:
      - name: secret-volume-mount
        secret:
          secretName: {{ .Values.secret.name }}
      {{- end}}