apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: {{ .Values.appName }}
    app.kubernetes.io/component: {{ .Values.appName }}
    app.kubernetes.io/instance: {{ .Values.appName }}
  name: {{ .Values.appName }}
spec:
  lookupPolicy:
    local: true