{{- if .Values.secret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
data:
  {{- range $key, $val := .Values.secret.values }}
  {{ $key }}: {{ $val | toString | b64enc | quote }}
  {{- end}}
{{- end}}